export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_PRODUCTS_FEATURE = 'FETCH_PRODUCTS_FEATURE';


export const FETCH_PRODUCTS_BESTDEAL = 'FETCH_PRODUCTS_BESTDEAL';

export const FETCH_PRODUCTS_BYCATEGORIES = 'FETCH_PRODUCTS_BYCATEGORIES';
export const FETCH_PRODUCT_NEW = 'FETCH_PRODUCT_NEW';
export const FETCH_PRODUCT_BESTSELL = 'FETCH_PRODUCT_BESTSELL';
export const FETCH_BANNER = 'FETCH_BANNER';
export const LOG_IN = 'LOG_IN';
export const DETAILS = 'DETAILS';
export const CART_INIT = 'CART_INIT';
export const CART_REMOVE = 'CART_REMOVE';
export const CART_UPDATE = 'CART_UPDATE';
export const CART_ADD = 'CART_ADD';
export const LOG_IN_FACEBOOK = 'LOG_IN_FACEBOOK'; 
export const ADD_WISH_LIST = 'ADD_WISH_LIST';
export const REMOVE_WISH_LIST = 'REMOVE_WISH_LIST';


