export const FETCH_PRODUCT_ADMIN = 'FETCH_PRODUCT_ADMIN';
export const FETCH_CATEGORY_ADMIN = 'FETCH_CATEGORY_ADMIN';
// export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
// export const FETCH_PRODUCTS_CATEGORY_FEATURE = 'FETCH_PRODUCTS_CATEGORY_FEATURE';
// export const LOG_IN = 'LOG_IN';
// export const DETAILS = 'DETAILS';

export const FETCH_ROOM = 'FETCH_ROOM';
export const LOG_IN_ADMIN = 'LOG_IN_ADMIN';
export const USER_INIT_ADMIN = 'USER_INIT_ADMIN';
export const ADD_NEW_ROOM = 'ADD_NEW_ROOM';
export const DELETE_PRODUCT_ADMIN = 'DELETE_PRODUCT_ADMIN';
export const FETCH_BRAND_ADMIN = 'FETCH_BRAND_ADMIN';
export const ADD_PRODUCT_ADMIN ='ADD_PRODUCT_ADMIN';
export const UPLOAD_IMAGE_ADMIN = 'UPLOAD_IMAGE_ADMIN';